# Generated by Django 5.0.4 on 2024-04-08 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='pais_nacimiento',
            field=models.CharField(default='', max_length=100),
        ),
    ]
