# Generated by Django 5.0.4 on 2024-04-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_persona_estado_civil_persona_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='apellido',
            new_name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombre',
        ),
        migrations.AddField(
            model_name='persona',
            name='primer_nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='segundo_apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='segundo_nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
